name: barahi
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_launcher_icons: ^0.7.5
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  get_it: ^4.0.4
  dartz: ^0.9.2
  http: ^0.12.2
  firebase_auth: ^0.20.1
  flutter_form_builder: ^3.14.1
  path: ^1.7.0
  firebase_storage: ^7.0.0
  image_picker: ^0.6.7+22
  cached_network_image: ^2.5.0
  shared_preferences:
  photo_view: 0.10.3
  cloud_firestore: ^0.16.0+1
  font_awesome_flutter: ^8.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


