name: barahi
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3
  flutter_launcher_icons: ^0.9.1
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  dartz: ^0.10.0-nullsafety.2
  http: ^0.13.3
  firebase_auth: ^3.0.1
  flutter_form_builder: ^6.0.1
  path: ^1.8.0
  firebase_storage: ^10.0.1
  image_picker: ^0.8.3
  cached_network_image: ^3.1.0
  photo_view: ^0.12.0
  cloud_firestore: ^2.4.0
  font_awesome_flutter: ^9.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/


